### ISSUE TITLE
Cancellation causes retry with default retry handler

### ISSUE THREAD

**Issue by acchou** [googleapis/gaxios#120]
#### Steps to reproduce

  1. Configure gaxios with an onRetryAttempt handler that logs to console.
  2. Create a gaxios request and then use the cancellation api (AbortController) to cancel it.
  3. Note that the console output indicates the request is an AbortError, and gaxios will attempt to retry the request.

I think this is likely an omission in `shouldRetryRequest`. While this function can be overridden, the default behavior is probably surprising.

**Comment by bcoe** [comment]
@acchou could I bother you to provide an example of the code that's causing this issue for you?

**Comment by acchou** [comment]
https://github.com/acchou/gaxios-issue-120

**Comment by acchou** [comment]
Here's the code that demonstrates the issue, in case you don't want to dig into the repo:
```typescript
import { AbortController } from "abort-controller";
import { GaxiosOptions, GaxiosError, request } from "gaxios";

function onRetryAttempt(err: GaxiosError) {
    console.log(`Retrying ${err}`);
}

async function main() {
    const source = new AbortController();
    const config: GaxiosOptions = {
        method: "GET",
        url: "https://google.com",
        signal: source.signal,
        retryConfig: { onRetryAttempt, retry: 10, noResponseRetries: 10 }
    };
    const req = request(config);
    source.abort();
    await req;
}

main();
```
