### ISSUE TITLE
ie11 Gaxios

### ISSUE THREAD

**Issue by Emiliano-Bucci** [googleapis/gaxios#126]
Hello! I'm currently encountering issues using this lib with IE11 (Nextjs, Apollo, GraphQL).  Basically i'm getting a `syntax` error and the breakpoint is being setted in the class `GaxiosError`. Any clue on this? Thanks :)

**Comment by bcoe** [comment]
@Emiliano-Bucci would you be able to provide the stack-trace from the syntax error that you're getting?

**Comment by JustinBeckwith** [comment]
Yeah, this is never going to work :(  We target a version of JavaScript that allows es6 classes, which AFAIK, are not supported on any version of internet explorer:
https://caniuse.com/#feat=es6-class

Sadly, I just don't think IE is something we can even attempt to support.  Apologies!
