### ISSUE TITLE
Add support for `Promise` on `onRetryAttempt()`

### ISSUE THREAD

**Issue by fivechjr** [googleapis/gaxios#144]
From this:
https://github.com/googleapis/gaxios/blob/7137a2d82f2905a8042ea97d4dcbc769b3f43a1b/src/retry.ts#L76-L78

To this:
```
if (config.onRetryAttempt) { 
   await config.onRetryAttempt(err); 
} 
```

**Comment by atjeff** [comment]
@JustinBeckwith any movement on this one?

**Comment by JustinBeckwith** [comment]
nope

**Comment by atjeff** [comment]
@JustinBeckwith would you accept a PR?

**Comment by JustinBeckwith** [comment]
I'm curious - what is the use case around this?  I think someone made the same change in [retry-axios](https://github.com/JustinBeckwith/retry-axios/commit/acfbe399f7017a607c4f49c578250a82834c448c), on which this retry logic was based.  I just can't for the life of me figure out what you would that needed to be async in here 😆 

The challenge here will be writing it in a way that isn't a breaking change.  Or, we should lump the change in with the node.js 8 deprecation.  Assuming we've figured all that stuff out, always love a PR!

**Comment by atjeff** [comment]
For me, I want to be able to detect that an OAuth2 token has been invalidated, and refresh it before retrying the request

**Comment by JustinBeckwith** [comment]
Ahhh, that actually makes sense!  We do a similar thing in our auth libraries.  PR would be lovely :)

**Comment by atjeff** [comment]
Thanks @JustinBeckwith ! I opened a PR, I didn't see that I broke any tests.
