### ISSUE TITLE
Make time units clear for retry configuration

### ISSUE THREAD

**Issue by Tyler-Murphy** [googleapis/gaxios#154]
No units are specified for the `retryDelay` option, which makes it hard to be sure what the value represents.

```
    // The amount of time to initially delay the retry.  Defaults to 100.
    retryDelay?: number;
```

I was using the option in a library that uses `gaxios` as a dependency of a dependency, so I had to dig through multiple layers to end up in the source code here to [confirm that it uses milliseconds](https://github.com/googleapis/gaxios/blob/d9b1a60d12e32f03e562229e4cf23efb9b7d9763/src/retry.ts#L72).

It'd be helpful for the units of the number to be in the option name, so that it's called something like `retryDelayMilliseconds`. Or even better, `initialRetryDelayMilliseconds`.

I didn't look through all other options to see whether they're missing units, but generally, I think it's helpful for all units to be specified wherever possible, to reduce ambiguity.

**Comment by JustinBeckwith** [comment]
That's a really great call, and thank you for the issue!  Kind of a good news / bad news update here.  Turns out - we were never actually using the `retryDelay` property (#143)

Instead of trying to nuance this in with the exponential backoff in place, we decided to remove the option all together in #203.

**Comment by Tyler-Murphy** [comment]
Oh no! Well, thanks for the update.

Are retries happening even though the `retryDelay` option wasn't doing anything? It sounds like they are, but I'd like to confirm it.

**Comment by JustinBeckwith** [comment]
Oh yeah, of course.  It's just that the backoff strategy I'm place appears to work pretty well, and I didn't want to mess with it.
