### ISSUE TITLE
Forced 'Content-Type' header

### ISSUE THREAD

**Issue by dragoncodes** [googleapis/gaxios#156]
Gaxios rewrites the `Content-Type` header when the payload is of type 'object' in `validateOpts`:

```
    if (opts.data) {
      if (this.isReadableStream(opts.data)) {
        opts.body = opts.data;
      } else if (typeof opts.data === 'object') { // <-- Here
        opts.body = JSON.stringify(opts.data);
        opts.headers['Content-Type'] = 'application/json';
      } else {
        opts.body = opts.data;
      }
    }
```

I am currently updating to the google publisher v3 API (NodeJS) and I've hit a snag. 
I am reading and passing the apk data as follows:

```
const apk = fs.readFileSync(apkFilePath);

this.publisher.edits.apks.upload({
           editId,
           packageName,
           media: {
               mimeType: 'application/vnd.android.package-archive',
               body: apk
            }
}, (err, res) => {});
```

In this case, I am explicitly specifying the `mimeType` to the one required by the upload API, `apk` variable is of type `Buffer`, but a `typeof` check returns 'object'. The upload API then returns 

```
Media type 'application/json' is not supported. Valid media types: [application/octet-stream, application/vnd.android.package-archive] 
```

I'm not sure why there's a need to force the header and serialization when the user has explicitly set them, maybe I am missing something though 🤔

**Comment by dragoncodes** [comment]
I tried to test the fix for the apk upload (Content-Type: application/vnd.android.package-archive), but another request can't go through because it's in `application/x-www-form-urlencoded`, but the data is still being stringified. 

This leads me to believe that a lot of users, including other libraries, have been relying on this behavior and changes may become "breaking". 

To test out the full procedure in my case I added a reversed flag `disableAutomaticHeaderResolution`:

```
   if (this.isReadableStream(opts.data)
                || this.opts.disableAutomaticHeaderResolution) { // <- this bit
                opts.body = opts.data;
            } else if (typeof opts.data === 'object') { ... }
```
It seems like a dirty fix, but it can then be adopted faster and safer.

**Comment by bcoe** [comment]
@dragoncodes I'm wondering if this might have changed since this issue was opened...

But you should be able to set a custom `content-type` header as long as you're providing a `string`, or readable stream body. (`Buffer` isn't actually a type accepted by the underlying `node-fetch` library, or at least it's not documented that it does).

So, I think you can modify your code to something like this, and it would work:

```js
const apk = fs.readFileSync(apkFilePath);

this.publisher.edits.apks.upload({
           editId,
           packageName,
           media: {
               mimeType: 'application/vnd.android.package-archive',
               body: apk.toString()
            }
}, (err, res) => {});
```

or,

```js
const apk = fs.readFile(apkFilePath);

this.publisher.edits.apks.upload({
           editId,
           packageName,
           media: {
               mimeType: 'application/vnd.android.package-archive',
               body: apk // <-- readable stream.
            }
}, (err, res) => {});
```

---

@CodeWithOz this library should work for you 👍

I'm pretty sure the problem described here was either:

1. missing documentation , or.
2. a bug with the upstream `googleapis` library, which uses `gaxios`.
