### ISSUE TITLE
function `isReadableStream` failed to judge the object returned from @google-cloud/storage's File.createReadStream

### ISSUE THREAD

**Issue by lushu** [googleapis/gaxios#160]
- OS: Mac OS
  - Node.js version: v11.6.0
  - npm version: v6.11.2
  - `gaxios` version: 2.0.1

#### Steps to reproduce

  1. I am using [google-api-nodejs-client](https://github.com/googleapis/google-api-nodejs-client) to upload file to [Google Analytics Data Import](https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/analytics/v3.ts). Basically, this API expects a readable stream to fulfill a HTTP POST (upload).
  2. It works fine when I use a local file, e.g. fs.createReadStream
  3. It will fail when I use Cloud Storage [@google-cloud/storage's file.createReadStream](https://github.com/googleapis/nodejs-storage/blob/b8faf3cb99d20c285839dbce40ab852147f0f9b1/src/file.ts#L1188). The Error message is "**Error: Media type 'application/json' is not supported. Valid media types: [application/octet-stream]**"

I have dug into the code and find the main reason is the function `isReadableStream` in gaxios.js. 
The object from @google-cloud/storage does have the `_read` function and act as a 'Readable', but it is not the instance of stream.Readable. So the function `isReadableStream` will always return false here and the request will be changed from `application/octet-stream` to `application/json`. 

I think the solution maybe:
- change the logic of this function
or
- create a Readable object based the object from  @google-cloud/storage (I am not sure this is a good idea)

Please kindly advise. Thanks!

**Comment by lushu** [comment]
Can I help with this feature? If it's possible, please let me know how. Thank you.

**Comment by stephenplusplus** [comment]
Hey @lushu, good catch. Thanks for opening this and offering to help. If you'd be willing to send a PR, I think the module `is-stream` could help us out: https://github.com/sindresorhus/is-stream/blob/master/index.js

**Comment by lushu** [comment]
@stephenplusplus Thank you. PR was submitted.
