### ISSUE TITLE
Real request information in response object

### ISSUE THREAD

**Issue by marapper** [googleapis/gaxios#187]
There is no way to know what real URL was fetched if maxRedirects/follow is setted. 

 **Is your feature request related to a problem? Please describe.**

When we try to parse relative links (it's a bad but real) in the crawled page we can not say how turn it out in absolute links.

 **Describe the solution you'd like**

Most we need real response URL after some redirects chain happens.

node-fetch Response have `url` property with final page URL.

axios response have `request` property as XMLHttpRequest object with final page URL in `responseURL` property.

So it can be done with limited and incomplete interface of XMLHttpRequest. Something like this https://github.com/marapper/gaxios/commit/836fca1d031769b03b65def22904de9d4d25dce4

 **Describe alternatives you've considered**
Full and comlete implementation of axios response? But it's not neccessary in most cases.

 **Additional context**

It could solve linkinator' issues https://github.com/JustinBeckwith/linkinator/issues/108

**Comment by marapper** [comment]
Is it any reason to not create PR for this?

**Comment by JustinBeckwith** [comment]
If I'm understanding all of this correctly, I think the original url should be available in `response.config.url`, right?

**Comment by marapper** [comment]
Yes. Same in the axios:

```
await axios.get('https://example.com/redirect')

{
 config: {
   url: '/redirect',
   ...
 },
 request: {
   responseURL: 'https://example.com/real_page',
 }
}
```

**Comment by bcoe** [comment]
@marapper we would definitely be open to a pull-request, if you'd like to take a shot at this.

**Comment by marapper** [comment]
simpliest implementation https://github.com/googleapis/gaxios/pull/189

but don't really understand why licence header is broken
