### ISSUE TITLE
Error when using GaxiosPromise as return type of async function

### ISSUE THREAD

**Issue by Maxim-Mazurok** [googleapis/gaxios#215]
#### Environment details

  - OS: Ubuntu 19.10
  - Node.js version: 10.16.3
  - npm version: 6.9.0
  - `gaxios` version: 2.2.0

#### Steps to reproduce

  1. 
```ts
submitAction = async (action: SubmitAction): 
  GaxiosPromise<sheets_v4.Schema$BatchUpdateSpreadsheetResponse> => { ... }
```
  2. 
```
Error: TS1055: Type 'GaxiosPromise' is not a valid async function return type in ES5/ES3 because it does not refer to a Promise-compatible constructor value.
```

Adding `export const GaxiosPromise = Promise;` in `common.d.ts` fixes the problem, but I'm not sure how to achieve this during the build process, hence no PR.
Got solution from here: https://github.com/microsoft/TypeScript/issues/12776#issuecomment-265885846

**Comment by JustinBeckwith** [comment]
Greetings!  It looks like you're targeting `ES3/ES5` with your TypeScript configuration.  I don't think that's going to work out with this library :) We require at least `ES2016` and above, which would have native Promise support.  

Can you share your `tsconfig`?

**Comment by Maxim-Mazurok** [comment]
Yes, Justin, you're totally right, thank you!
I was targeting `ES5`:

```json
{
  "compilerOptions": {
    "target": "es5",
    ...
  },
  ...
}
```

after changing it to `es2016` and adding `import { GaxiosPromise } from 'gaxios';` everything worked like a charm.
Thanks again, cheers!

**Comment by Maxim-Mazurok** [comment]
Not sure why I was assigned to this 😀
As far as I remember, it was resolved...
