### ISSUE TITLE
case sensitivity of headers should not matter

### ISSUE THREAD

**Issue by bcoe** [googleapis/gaxios#262]
Currently if one were to set a "content-type" header and a "Content-Type" header, the two are not equivalent.

I've seen libraries like `express` approach this differently, such that `headers` are case-insensitive.

**Comment by kungfutse** [comment]
Headers are case-insensitive according to RFC2616 so this is a bug, not a feature request, in my opinion.

**Comment by JustinBeckwith** [comment]
I'm not sure what the actual bug is here :) Can someone give me an example?  Right now the `request.Headers` field is just a POJO.  

For example:

```js
const options: GaxiosOptions = { 
  headers: {
    'content-type': 'application/json',
    'Content-Type': 'text/xml',
  },
},
```

We could look for this situation and throw if we find duplicate keys once lower cased?

**Comment by bcoe** [comment]
@JustinBeckwith a warning might be enough, but I think a cleaning step that lowercases headers would be good, that way upstream libraries that build on top of gaxios, e.g., google-auth-library need not check every combination of a given header.

**Comment by danielbankhead** [comment]
We should the native [`Headers`](https://developer.mozilla.org/en-US/docs/Web/API/Headers) class to resolve this; we'll look into this in the major after next 😉
