### ISSUE TITLE
Invalid_grant error with untagged version 2.3.3

### ISSUE THREAD

**Issue by baflo** [googleapis/gaxios#267]
Hello, a few days ago we started getting these errors: `Getting metada from plugin failed with error: unsupported_grant_type: Invalid grant_type`. It took a while, but we're able to pin it down to `gaxios` which apparently got an update from `2.3.2` to `2.3.3`. Once downgraded, the error disappeared again.

I also found there's no tag for a version `2.3.3` in this repository to search for the error. 

#### Environment details

  - OS: Debian Stretch
  - Node.js version: 10.16.3
  - npm version: 6.9.0
  - `gaxios` version: 2.3.3

#### Steps to reproduce

  1. npm install gaxios@^2.3
  2. Installs `gaxios@2.3.3`

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by bcoe** [comment]
👋 hey @baflo there's a known issue with `gaxios@2.3.3`, `2.3.4` was released to fix the issue and is published to `npm`.

We currently only tag the mainline releases of libraries, which for gaxios is currently `3.0.2` (which also has the fix). `2.x.x` is now being used to backport fixes for Node 8, as which we're in the process of deprecating.

If you make sure you are on version `2.3.4` of the library, things should work for you as expected.
