### ISSUE TITLE
How is gaxios compared to got and other libraries?

### ISSUE THREAD

**Issue by Nisthar** [googleapis/gaxios#294]
How is gaxios compared to got and other libraries performance wise?

**Comment by JustinBeckwith** [comment]
Performance is a tricky thing to measure :) 

This library was optimized for reducing server load time, specifically in serverless environments.  It takes about 7ms to load:
![image](https://user-images.githubusercontent.com/534619/82765556-b859bf00-9dcc-11ea-908b-e4b179b99c91.png)

Got is a *great* HTTP library.  It has a lot of features, and does a lot of things for you.  It takes about 60ms to load, has a slightly more complex require tree:
![image](https://user-images.githubusercontent.com/534619/82765542-a7a94900-9dcc-11ea-80c4-73a35c553921.png)

In terms of performance on the wire, I'd wager it really depends!  Under the hood, gaxios is using `node-fetch` so it's performance characteristics are likely to match those of `node-fetch` with a tiny amount of drift for our own code.  There are likely places where got (which is far more popular btw) is better, and probably places gaxios is better.  For instance, I know that got supports HTTP/2 natively which could have significant performance gains in some scenarios.  

It's worth asking what performance characteristics are really important to you.  Is it binary load time?  Cold start?  Time to get a request on the wire?  From there, I'd suggest playing with the profiling tools in chrome to see which one works best for you.  

Hope this helps!
