### ISSUE TITLE
How to Pipe an Express Post Request into a Gaxios Post Request

### ISSUE THREAD

**Issue by shijumon** [googleapis/gaxios#308]
I am using Gaxios NPM http library for a NodeJS TypeScript project.

I would like to know how to pipe an Express Post Request into a Gaxios Post Request. I am tried to implement the same as in the following code

 ```
private async promisifyRequest(inputRequest?: express.Request): Promise<any> {
    const requestOptions: GaxiosOptions = {};
    requestOptions.url = 'http://localhost/api/upload';
    requestOptions.method = 'POST';
    requestOptions.responseType = 'json';
    const data = await new Promise((resolve, reject) => {
      inputRequest.pipe(
        request(options).then(
          (value) => { resolve(value); },
          (reason) => { reject(reason); }
        );
    );
    return data;
  }
```

But it shows compiler error `Argument of type 'Promise' is not assignable to parameter of type 'WritableStream'.

I am trying to switch from Request library to Gaxios Library as the Request Library is now deprecated.

Here is the working code, which is implemented using Request Library
Here the inputRequest is `inputRequest: express.Request` and post is `import { post } from 'request';`

```
 const data = await new Promise((resolve, reject) => {
      if (inputRequest) {
        inputRequest.pipe(post(url, options, (error, response, body) => {
          if (response) {
            resolve(response);
          } else {
            reject(error);
          }
        }));
      }
    });
```

**Comment by JustinBeckwith** [comment]
Greetings!  Should look something like this:

```ts
import * as express from 'express';
import {request} from 'gaxios';

const app = express();
const port = 3000;

app.get('/', async (req, res) => {
  const exampleResponse = await request({
    url: 'http://example.com/',
    method: 'POST',
    body: req,
  });
  res.status(exampleResponse.status).send(exampleResponse.data);
});

app.listen(port, () => {
  console.log(`Example app listening at http://localhost:${port}`);
});
```

Want to give that a shot and let me know how it goes?

**Comment by sofisl** [comment]
I'll close this for now, feel free to reopen @shijumon if this doesn't address your concern!
