### ISSUE TITLE
Slow down initial retry attempt

### ISSUE THREAD

**Issue by pebo** [googleapis/gaxios#333]
Currently gaxios attempts the first retry without delay:https://github.com/googleapis/gaxios/blob/5b586d52b1798b6edf2bec7e59402e4d4115c8ee/src/retry.ts#L64

As `config.currentRetryAttempt` is `0` after the first failure the first delay will be 0ms.

If often makes sense to wait a little while before making a retry e.g. if the services responds with 429 or 503. It would be nice if retry.ts was less aggressive by default.

A workaround now is to set  retryConfig.currentRetryAttempt to a non-zero value, e.g 1 before making the call to gaxios.request() but this relies on the internal implementation of the backoff logic and you'd also need to adjust retryConfig.retry..

Could the default retry implement instead be adjusted with a minimum delay value or make the backoff calculation configurable with a function that could be overridden in retryConfig e.g. something like:
```
function backoffDelay(currentRetryAttempt: number) {
  return ((Math.pow(2,currentRetryAttempt) - 1) / 2) * 1000;
}
```

**Comment by bcoe** [comment]
I agree that we should probably stagger the first retry attempt by a few ms.
