### ISSUE TITLE
bug: update GaxiosError code to include a string or a number

### ISSUE THREAD

**Issue by sofisl** [googleapis/gaxios#393]
We need to allow either string or number representation for [GaxiosError code](https://github.com/googleapis/gaxios/blob/18a48fc298c8d0e707b7f6e5cd892cb7c239f1db/src/common.ts#L21).

See this PR describing the problem: https://github.com/googleapis/google-auth-library-nodejs/pull/1165

This is the original bug: https://github.com/googleapis/google-auth-library-nodejs/issues/1092

This will be a breaking change, so we need to wait until the next major version to make this change.

**Comment by bcoe** [comment]
Making `p3`, since our intention is to drop Node 10 in 6 months.

**Comment by sofisl** [comment]
Relabeling as a FR since it's not breaking anyone's functionality currently, but will be a bug we correct in the next version.

**Comment by danielbankhead** [comment]
Fixed in https://github.com/googleapis/gaxios/pull/552
