### ISSUE TITLE
Accessing Google APIs using Auth Key

### ISSUE THREAD

**Issue by ShaikhSuf** [googleapis/gaxios#408]
**PLEASE READ**: This is more of a question than a Bug Report. 

***API end-point Authentication***  

#### API End Point - https://cloud.google.com/healthcare/docs/reference/rest/?apix=true

I'm working on a project to publish/subscribe Application data to/from google health APIs. The API end-point has examples to use from the backed services but doesn't have any guidance on the front-end applications. 

I tried, end-points in Postman using OAuth authorization, and it works (It requires user intervention). But the Auth_key authorization doesn't work and throwing the following error:-

{
    "error": {
        "code": 401,
        "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
        "status": "UNAUTHENTICATED"
    }
}

I use Axios library to access other services from the application using the Auth_Key authorization. But no clue how to use that against the Google APIs. I did extensive research to find an example, but no luck whatsoever.  

Below is my use case:-
- Serverless Architecture (We will have no backend services)
- We will have only front-end code. Mostly Next.js for Web App and React Native for Mobile App.
- Publishing and subscribing Application data to/from Google APIs using packages like Axios. 

# Below is a similar code snippet - 
      const response = await axios({
          url: 'API-End-Point-URL',
          method: 'post/get/del',
          headers: {
              'content-type': 'application/json',
              authorization: 'Bearer 00V5dw-p7Y3YsW3VQr8lci_G4uQS9hyRNdGkUPmwpe'
          },
          params: {
              'activate': true
          },
          data: payloaddata
          })

Any help will be appreciated. 

Thanks!
-Sufian.

**Comment by bcoe** [comment]
@ShaikhSuf here's some sample code you should be able to use as a starting point:

https://github.com/googleapis/google-api-nodejs-client/blob/master/samples/oauth2.js

The important thing is that you specify the appropriate scopes for the healthcare API, here's an example from the API:

https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/healthcare/v1.ts#L1778
