### ISSUE TITLE
How do I change the default adapter to Node `http` instead of `XHR` or `fetch`

### ISSUE THREAD

**Issue by m4heshd** [googleapis/gaxios#420]
I'm using the `@googleapis/drive` package with my Electron app and currently stuck on this irritating issue. I need the data body in response to be a Node.js `Stream` instead of a `ReadableStream`. I unfortunately can't seem to make this happen in the renderer process since `XHR` and `fetch` is available there. It's such a pain involving IPC for such simple task. I know `axios` has a simple solution for this but what do I need to do here? 

My code looks like this.

```js
drive.files.get({
            fileId: FILE_ID,
            alt: 'media'
        }, {
            responseType: 'stream',
            adapter:  // HOW DO I SET THE DEFAULT TO `http` HERE?
        }).then(res => {
            const dest = fs.createWriteStream(filePath);

            res.data
                .on('data', (data) => {
                    //.... show progress
                })
                .pipe(dest);
        })
```

#### Environment details

  - OS: All
  - Node.js version: 14.x
  - npm version: 7.x
  - `gaxios` version: 4.3.0

#### Steps to reproduce

  1. Create an Electron app with `google-api-nodejs-client`
  2. Try to use anything that returns a `stream`

**Comment by bcoe** [comment]
@JustinBeckwith can correct me if I'm wrong, but I don't believe this is currently supported by gaxios.

**Comment by m4heshd** [comment]
That's pretty inconvenient when a "nodejs" client not returning a Node.js stream. Oh well. 😞

**Comment by m4heshd** [comment]
@bcoe just to be clear, this is because of the default behavior of `node-fetch` right?

**Comment by bcoe** [comment]
@m4heshd how does axios approach this problem? out of curiosity, this would help us understand the interface you're advocating.

**Comment by m4heshd** [comment]
@bcoe On `axios` you can override the default adapter.

```js
import httpAdapter from 'axios/lib/adapters/http';
axios.defaults.adapter = httpAdapter;
```

**Comment by m4heshd** [comment]
@bcoe I just discovered `fetchImplementation` option. So `gaxios` is already capable of meeting my requirement. I just need to do this.

```js
const nodeFetch = require('node-fetch/lib/index').default;

drive.files.create({
            requestBody: {...fileMetadata},
            media: media,
            fields: 'id'
        }, {
            fetchImplementation: nodeFetch
        }).then((resp) => {
            resolve(resp.data.id);
        }).catch((error) => {
            reject(error);
        });
```

So `gaxios` is good. Now the only issue is with how [`isBrowser()`](https://github.com/googleapis/nodejs-googleapis-common/blob/98edc86818868aaedd291268b79347298d84b95f/src/isbrowser.ts#L14) is implemented.

Closing this.
