### ISSUE TITLE
Full support for axios replacement (haxios ;-))

### ISSUE THREAD

**Issue by simllll** [googleapis/gaxios#446]
**Is your feature request related to a problem? Please describe.**
Right now it's not possible to use gaxois as a drop-in replacmenet for axios, as there are some core things missing:
* get, post, etc helper methods are not available
* there is no built-in support for interceptors
* not all config options are supported
 
 **Describe the solution you'd like**
Allow an (almost) identical API of current axios, to allow gaxios as an 1:1 replacement.

I added the missing functionality in "haxios" which is based on gaxios: https://github.com/hokify/haxios 

My question now is: are you interested in bringing this into gaxios? Or is this by design not supported? If so ,what are the reasoning for it? If not, how can I help to make this happening? :)

**Comment by danielbankhead** [comment]
Ultimately we would like to transition this library to be an interface on top of `fetch` for cross-platform compatibility:
- https://github.com/googleapis/gaxios/issues/625

Thanks for your feedback
