### ISSUE TITLE
onUploadProgress not working

### ISSUE THREAD

**Issue by simllll** [googleapis/gaxios#448]
onUploadProgress is actually not really possible right now with fetch, but gaxios types actually suggest it has implemented a case.

Possible solution:
remove type defintiion for onUploadProgress

**Comment by SurferJeffAtGoogle** [comment]
Could you provide a link to the type definitions?

**Comment by simllll** [comment]
https://github.com/googleapis/gaxios/blob/main/src/common.ts#L94
