### ISSUE TITLE
Update node-fetch to fix security issue

### ISSUE THREAD

**Issue by enahsor** [googleapis/gaxios#466]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

#### Environment details

  - OS: macOS Monterey (12.1)
  - Node.js version: 16.8.0
  - npm version: 7.21.0
  - `gaxios` version: 4.3.2

#### Steps to reproduce

The latest release of node-fetch fixes an information exposure issue. This library is currently on version 2 of that package but the fix happens in v3.

[more info](https://github.com/node-fetch/node-fetch/releases/tag/v3.1.1)

**Comment by sebiniemann** [comment]
I don't think it needs an update to node-fetch v3 (even though I personally would like to use the latest version).

node-fetch has released a patch in version 2.6.7. (https://github.com/node-fetch/node-fetch/releases/tag/v2.6.7, 8 days ago), which can already be used with this project without any changes (the `package.json` of this project allows all v2 versions, starting from 2.6.5). This only requires an update of the dependencies in user land.
