### ISSUE TITLE
Upgrade node-fetch dependency to v3.2

### ISSUE THREAD

**Issue by adarshmadrecha** [googleapis/gaxios#508]
**Is your feature request related to a problem? Please describe.**
When using firebase-admin in Nuxt3 Project along with Mongoose, it causes clash becase of use of different versions of `node-fetch` by underlying libraries.

![image](https://user-images.githubusercontent.com/11911938/196038539-f063f819-0490-4905-85e6-3daf0b781d39.png)
![image](https://user-images.githubusercontent.com/11911938/196038565-741d38dc-9ee0-4fd0-a0c2-1dbc5e74e088.png)

 **Describe the solution you'd like**
Upgrade to latest version of `node-fetch` i.e. `3.2.x`

 **Describe alternatives you've considered**
Have added `overrides` in the package.json, but it does not work because of the way it is imported in the gaxios.
```
"overrides": {
      "node-fetch": "3.2.10"
 }
```
![image](https://user-images.githubusercontent.com/11911938/196038684-9458066a-1ddd-46cb-a1fa-b6deb7d704f9.png)

 **Additional context**

**Comment by ddelgrosso1** [comment]
Hi @adarshmadrecha thanks for opening this issue. Currently we are unable to update to node-fetch 3.x as it has moved to a pure ESM package. Please see https://github.com/googleapis/gaxios/issues/429 for additional context.

**Comment by mbrevda** [comment]
>  as it has moved to a pure ESM package

It would be great if you can elaborate more on how moving to a pure esm package creates a blocker?

**Comment by adarshmadrecha** [comment]
As mentioned in https://github.com/googleapis/gaxios/issues/429#issuecomment-1833097220
Starting with node v21, this issue will have to be resolved.
