### ISSUE TITLE
Ensuring compliance with SNI Extension requirement on remote host

### ISSUE THREAD

**Issue by drmrbrewer** [googleapis/gaxios#518]
One of my node apps sends requests to a remote service using the `gaxios` module, and I recently had a notice from the service provider to say that "we will be requiring that SNI extensions be enabled for all API requests".  

I'm slightly out of my depth here, and don't know whether any changes will be required on my side to ensure compliance.

From my very limited understanding, I'm thinking/hoping that SNI is *already used* by default when sending requests using `gaxios`, at least where the request URL is specified using the domain name rather than an IP address.

Sources:

- [What is SNI?](https://knowledge.digicert.com/quovadis/ssl-certificates/ssl-general-topics/what-is-sni-server-name-indication.html)

- gaxios is [based on `node-fetch`](https://github.com/googleapis/gaxios#gaxios)

- with [`node-fetch` the `servername` for SNI can be specified in the http `agent`](https://github.com/node-fetch/node-fetch/issues/218#issuecomment-270293945)

- [related example of creating an http `agent`](https://stackoverflow.com/a/46857299/4070848) (in this case to *disable* SNI rather than *enable* it, but hey)

- with `gaxios` you can indeed [pass a custom `agent` in the request options](https://github.com/googleapis/gaxios#request-options)

- when creating an `agent` with `New agent()` [you can pass `servername` as an option but it **defaults to the hostname** if supplied in the URL](https://nodejs.org/api/https.html#new-agentoptions):

> **`servername`**: [<string>](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type) the value of [Server Name Indication extension](https://en.wikipedia.org/wiki/Server_Name_Indication) to be sent to the server. Use empty string `''` to disable sending the extension. **Default**: host name of the target server, unless the target server is specified using an IP address, in which case the default is `''` (no extension).

So, if my request options for the `gaxios` request is in the following form:

    { url: 'https://api.example.com/getData/xyz/mykey' }

... then I should already be complying with the SNI requirements at the remote host (because I'm specifying the hostname `api.example.com` in the URL) without having to bother with custom agents (or anything else)?

Any help appreciated!  Thanks.

**Comment by ddelgrosso1** [comment]
Hi @drmrbrewer thank you for the question. I took a look at all the resources you provided and I would draw the same conclusion as you have come to. If you are not explicitly disabling SNI by setting `servername` to an empty string (or using an IP address) there should be nothing further for you to do. Gaxios does not make any changes to this value. As you noted Gaxios utilizes Node-fetch which in turn utilizes Node:https. Hope this helps. Please let me know if you need anything further.

**Comment by drmrbrewer** [comment]
Hi @ddelgrosso1 thanks so much for casting an eye over my rambling thoughts.  It's reassuring to know that you are of the same view as me.  Fingers crossed :-)

**Comment by ddelgrosso1** [comment]
@drmrbrewer I am going to close out this issue. If anything additional comes up, please feel free to reopen.
