### ISSUE TITLE
Get request with one-item array param, will send the value inside instead the the array 

### ISSUE THREAD

**Issue by choyzer** [googleapis/gaxios#521]
#### Environment details
  - OS: macOS 
  - Node.js version: v18.12.1
  - npm version: 8.19.2
  - `gaxios` version: 5.0.2

#### Steps to reproduce

Send a simple `GET` request with an one-item-array as part of the params using `gaxios`
`http://localhost/someEndpoint?account_ids[]=Y&shopId=X`

The server is getting the request (`someEndpoint`), will get `account_ids=Y`, instead of `account_ids =[Y]`
The `req.query.account_ids` will be equal Y instead [Y]

This is happening only on arrays with one item, in multiple items are working fine

In `axios` it's working fine.

**Comment by sofisl** [comment]
Hi @choyzer, thanks for submitting this. For our use case, I think this is working as intended. We use the `paramsSerializer` method from the Node core library, which parses arrays in [this way](https://nodejs.org/api/querystring.html#querystringstringifyobj-sep-eq-options):

```
querystring.stringify({ foo: 'bar', baz: ['qux', 'quux'], corge: '' });
// Returns 'foo=bar&baz=qux&baz=quux&corge='
```

So it actually always returns single elements without an array. Testing this locally, this request:

```
   const res = await request({
      url,
      params: {querystring: ['a', 'b']},
    });
```

returns:

```
https://example.com/?querystring=a&querystring=b
```
and

```
   const res = await request({
      url,
      params: {querystring: ['a', 'b']},
    });
```
returns 

```
https://example.com/?querystring=a
```

For some more insight, in our cases, an array is a repeated field so when query string is encoded, it's literally repeated. If you really wanted to include the brackets, you could JSON.stringify the parameter and pass it as a string.

Hope this helps, feel free to reopen if you feel this still isn't resolved!
