### ISSUE TITLE
Support encoding

### ISSUE THREAD

**Issue by nguymin4** [googleapis/gaxios#58]
Hi @JustinBeckwith,

In your PR for `googleapis` https://github.com/googleapis/google-api-nodejs-client/pull/1558, it's written that `gaxios` supports `encoding` option. But I don't see it anywhere in `gaxios`. Am I misunderstanding something here?

Thanks

**Comment by JustinBeckwith** [comment]
Greetings!  Those were some out dated docs...
https://github.com/googleapis/google-api-nodejs-client/pull/1765

there's no `encoding` option directly on `gaxios`.
