### ISSUE TITLE
feat: Updated `timeout` Implementation and Documentation

### ISSUE THREAD

**Issue by rhodgkins** [googleapis/gaxios#602]
Is the `timeout` option used at all?

https://github.com/googleapis/gaxios/blob/ef40c61fabf0a48b2f08be085ee0c56dc32cf78c/src/common.ts#L180

From a [quick search](https://github.com/search?q=repo%3Agoogleapis%2Fgaxios%20timeout&type=code) and scan of the code I can't see how it's used? It's not an option in `node-fetch` either...

**Comment by danielbankhead** [comment]
It looks like it was passed to [`node-fetch` v2](https://github.com/node-fetch/node-fetch/tree/2.x) here:

https://github.com/googleapis/gaxios/blob/8490f242e798a3338642c689a1b3ffc15cbfd447/src/gaxios.ts#L139-L142

However, we should update this to work with any fetch implementation - I'll convert this to a feature request.

## Implementation Notes
- All modern `fetch` implementations offer a `signal` param: https://developer.mozilla.org/en-US/docs/Web/API/fetch
- `AbortSignal.timeout()` looks like a good option: https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/timeout_static (note the unique `TimeoutError` thrown)
- We can combine the timeout abort signal with a user's abort signal with `AbortSignal.any()`: https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/any_static
