### ISSUE TITLE
feat: Add `client_secret` to `defaultErrorRedactor`

### ISSUE THREAD

**Issue by khitrenovich** [googleapis/gaxios#604]
**Is your feature request related to a problem? Please describe.**

We recently realized that while some sensitive data is being filtered automatically from being logged, we see `client_secret` data fields are not. Upon some digging into the `gaxios` code, I found that `defaultErrorRedactor` is built to redact errors and is responsible for masking the rest of the fields, but `client_secret` is not handled. 

 **Describe the solution you'd like**

I would like `defaultErrorRedactor` to mask `client_secret` (or maybe just any `/secret/` field). This will benefit all the customers.

 **Describe alternatives you've considered**

Alternative is to implement own error redactor, duplicating the code that is already there, and mask `client_secret` too. Then we will have to use it everywhere we use `gaxios`, which is error-prone since it is easy to miss places. Same goes for an alternative to redact the error object after it was already thrown.

 **Additional context**

N/A

**Comment by danielbankhead** [comment]
I think this is a worthwhile security enhancement - thanks for filling! Once we have some bandwidth we'll work on adding this via a `/secret/` regex.

**Comment by danielbankhead** [comment]
Circling back, opened a PR to resolve:
- https://github.com/googleapis/gaxios/pull/609
