### ISSUE TITLE
How to add debugs logs to all requests

### ISSUE THREAD

**Issue by henhal** [googleapis/gaxios#655]
So I guess `gaxios` wraps `axios`, but when I try to enable debug logs for all requests using `axios-debug-log`, nothing happens.
Is there another way to globally turn on HTTP debug logs so that logs appear when using e.g. the `@googleapis/calendar` SDK?

**Comment by danielbankhead** [comment]
Thanks for your inquiry - `gaxios` actually doesn't wrap `axios`. Instead, you can use something like `NODE_DEBUG=http` to log HTTP requests

**Comment by henhal** [comment]
Thanks, didn't even think about that. Closing!
